import { getFishArchetype } from "./fishArchetypes.js";

// Fish data and roll helpers. Adding a new species only requires one new object
// in fishDatabase with its locations, zones, rarity, economy values, and
// optional `archetype` such as "eel", "flat", "torpedo", "round", or "longfin".
export const RARITY_META = Object.freeze({
  Common: {
    label: "Common",
    className: "rarity-common",
    color: "#d8e1d2",
    difficulty: 0.1,
    priceScale: 1,
  },
  Uncommon: {
    label: "Uncommon",
    className: "rarity-uncommon",
    color: "#78d27d",
    difficulty: 0.24,
    priceScale: 1.22,
  },
  Rare: {
    label: "Rare",
    className: "rarity-rare",
    color: "#59c7f2",
    difficulty: 0.42,
    priceScale: 1.55,
  },
  Epic: {
    label: "Epic",
    className: "rarity-epic",
    color: "#b798ff",
    difficulty: 0.62,
    priceScale: 2.05,
  },
  Legendary: {
    label: "Legendary",
    className: "rarity-legendary",
    color: "#f5c95c",
    difficulty: 0.82,
    priceScale: 2.9,
  },
  Mythical: {
    label: "Mythical",
    className: "rarity-mythical",
    color: "#ff7dcb",
    difficulty: 0.98,
    priceScale: 3.75,
  },
  Secret: {
    label: "Secret",
    className: "rarity-secret",
    color: "#ffffff",
    difficulty: 1.12,
    priceScale: 5.2,
  },
});

export const LOCATION_META = Object.freeze({
  harbor: {
    id: "harbor",
    name: "Рибальська Гавань",
    icon: "HB",
    tag: "Базар і Корабель",
    requiredLevel: 1,
    requiredBoat: null,
    travelCost: 0,
    biteTempo: 1.05,
    reelDifficulty: -0.02,
    description: "Жвавий причал із яткою торговця рибою, ліхтарями та кораблями далекого плавання.",
    palette: {
      skyTop: "#689ac2",
      skyBottom: "#f2d8b8",
      waterTop: "#1e6b88",
      waterBottom: "#0e3a4d",
      shore: "#584236",
      accent: "#f5c95c",
      haze: "rgba(255, 230, 180, 0.28)",
    },
    weatherWeights: { clear: 5, mist: 2, rain: 1, night: 1 },
  },
  lake: {
    id: "lake",
    name: "Reed Lake",
    icon: "LK",
    tag: "Starter",
    requiredLevel: 1,
    requiredBoat: null,
    travelCost: 10,
    biteTempo: 1,
    reelDifficulty: 0,
    description: "Warm reeds, soft light, and forgiving starter fish.",
    palette: {
      skyTop: "#8ed0cf",
      skyBottom: "#f4d09b",
      waterTop: "#238fa4",
      waterBottom: "#145464",
      shore: "#516a46",
      accent: "#f5c95c",
      haze: "rgba(255, 232, 178, 0.32)",
    },
    weatherWeights: { clear: 5, mist: 2, rain: 1, night: 1 },
  },
  bog: {
    id: "bog",
    name: "Болотне Озеро",
    icon: "BG",
    tag: "Рівень 3",
    requiredLevel: 3,
    requiredBoat: null,
    travelCost: 35,
    biteTempo: 0.95,
    reelDifficulty: 0.04,
    description: "Таємниче озеро серед топей з лататтям, блукаючими вогниками та густим туманом.",
    palette: {
      skyTop: "#526242",
      skyBottom: "#8b8555",
      waterTop: "#3e4d28",
      waterBottom: "#172414",
      shore: "#3d3121",
      accent: "#9bd267",
      haze: "rgba(115, 180, 75, 0.35)",
    },
    weatherWeights: { clear: 1, mist: 5, rain: 3, night: 2 },
  },
  swamp: {
    id: "swamp",
    name: "Murkfen Swamp",
    icon: "SW",
    tag: "Level 2",
    requiredLevel: 2,
    requiredBoat: "marsh-skiff",
    travelCost: 20,
    biteTempo: 0.92,
    reelDifficulty: -0.04,
    description: "Slow, muddy water with rare things hiding under lilies.",
    palette: {
      skyTop: "#9aa66b",
      skyBottom: "#c7b37a",
      waterTop: "#65783f",
      waterBottom: "#263a2e",
      shore: "#4a3f2a",
      accent: "#b7c984",
      haze: "rgba(141, 157, 88, 0.34)",
    },
    weatherWeights: { clear: 2, mist: 4, rain: 3, night: 1 },
  },
  river: {
    id: "river",
    name: "Copper River",
    icon: "RV",
    tag: "Skiff",
    requiredLevel: 2,
    requiredBoat: "river-skiff",
    travelCost: 30,
    biteTempo: 1.08,
    reelDifficulty: 0.02,
    description: "Fast bends, copper banks, and darting current fish.",
    palette: {
      skyTop: "#9fc6dd",
      skyBottom: "#e6cfc0",
      waterTop: "#4d927f",
      waterBottom: "#214c57",
      shore: "#815f3f",
      accent: "#ff9b62",
      haze: "rgba(255, 155, 98, 0.22)",
    },
    weatherWeights: { clear: 4, mist: 1, rain: 3, night: 1 },
  },
  mountain: {
    id: "mountain",
    name: "Frostpeak Lake",
    icon: "MT",
    tag: "Level 4",
    requiredLevel: 4,
    requiredBoat: "mountain-pass",
    travelCost: 50,
    biteTempo: 0.88,
    reelDifficulty: 0.16,
    description: "Cold, valuable fish with quick turns and less mercy.",
    palette: {
      skyTop: "#b7d7e8",
      skyBottom: "#f2f7f4",
      waterTop: "#6aa9bf",
      waterBottom: "#1f5770",
      shore: "#5c6f7d",
      accent: "#d9edf0",
      haze: "rgba(217, 237, 240, 0.36)",
    },
    weatherWeights: { clear: 3, mist: 2, rain: 1, night: 2 },
  },
  ocean: {
    id: "ocean",
    name: "Opal Coast",
    icon: "OC",
    tag: "Level 4",
    requiredLevel: 4,
    requiredBoat: "ocean-sloop",
    travelCost: 75,
    biteTempo: 0.94,
    reelDifficulty: 0.06,
    description: "Open surf, bigger weights, and long-distance casts.",
    palette: {
      skyTop: "#78a9d4",
      skyBottom: "#ffe2b8",
      waterTop: "#1d7fa9",
      waterBottom: "#0a3554",
      shore: "#c18454",
      accent: "#78d27d",
      haze: "rgba(120, 210, 125, 0.22)",
    },
    weatherWeights: { clear: 4, mist: 1, rain: 2, night: 2 },
  },
  coral: {
    id: "coral",
    name: "Coral Bay",
    icon: "CB",
    tag: "Level 6",
    requiredLevel: 6,
    requiredBoat: "reef-cutter",
    travelCost: 110,
    biteTempo: 1.04,
    reelDifficulty: 0.12,
    description: "Bright reef water with precious fish and sharper fights.",
    palette: {
      skyTop: "#80d7cf",
      skyBottom: "#ffd0a6",
      waterTop: "#1fa6b7",
      waterBottom: "#114c76",
      shore: "#e08f72",
      accent: "#ff7d67",
      haze: "rgba(255, 125, 103, 0.3)",
    },
    weatherWeights: { clear: 5, mist: 1, rain: 1, night: 3 },
  },
  abyss: {
    id: "abyss",
    name: "Gloam Trench",
    icon: "AB",
    tag: "Level 8",
    requiredLevel: 8,
    requiredBoat: "abyss-lantern",
    travelCost: 160,
    biteTempo: 0.78,
    reelDifficulty: 0.18,
    description: "Deep water where rare fish glow before they run.",
    palette: {
      skyTop: "#1a2038",
      skyBottom: "#5f557a",
      waterTop: "#173c5d",
      waterBottom: "#06131f",
      shore: "#2f3441",
      accent: "#b798ff",
      haze: "rgba(183, 152, 255, 0.24)",
    },
    weatherWeights: { clear: 1, mist: 2, rain: 1, night: 5 },
  },
  cavern: {
    id: "cavern",
    name: "Підземне Озеро",
    icon: "CV",
    tag: "Рівень 10+",
    requiredLevel: 10,
    requiredBoat: null,
    travelCost: 200,
    biteTempo: 1.12,
    reelDifficulty: 0.24,
    description: "Величне підземне озеро у глибинах печери з сяючими кристалами та реліктовими видами.",
    palette: {
      skyTop: "#0b0c16",
      skyBottom: "#171426",
      waterTop: "#124958",
      waterBottom: "#061b23",
      shore: "#20232e",
      accent: "#4ee8d7",
      haze: "rgba(78, 232, 215, 0.22)",
    },
    weatherWeights: { clear: 1, mist: 3, rain: 1, night: 5 },
  },
});

export const CAST_ZONES = Object.freeze([
  { id: "near", name: "Near Water", minPower: 0, maxPower: 0.42 },
  { id: "far", name: "Outer Ripple", minPower: 0.42, maxPower: 0.74 },
  { id: "deep", name: "Deep Water", minPower: 0.74, maxPower: 1 },
]);

export const fishDatabase = Object.freeze([
  {
    id: "reed-minnow",
    name: "Reed Minnow",
    rarity: "Common",
    minWeight: 0.2,
    maxWeight: 1.1,
    basePrice: 9,
    locations: ["lake"],
    zones: ["near"],
    chance: 44,
    xp: 8,
    description: "A tiny reed-line fish that flashes like a coin in shallow water.",
    colors: ["#e6e7a4", "#708944"],
  },
  {
    id: "glass-bluegill",
    name: "Glass Bluegill",
    rarity: "Common",
    minWeight: 0.4,
    maxWeight: 1.8,
    basePrice: 13,
    locations: ["lake"],
    zones: ["near", "far"],
    chance: 34,
    xp: 10,
    description: "Its pale fins look almost transparent when it rolls near the bobber.",
    colors: ["#a2d9e7", "#2b7188"],
  },
  {
    id: "amber-carp",
    name: "Amber Carp",
    rarity: "Uncommon",
    minWeight: 1.2,
    maxWeight: 5.5,
    basePrice: 27,
    locations: ["lake"],
    zones: ["far"],
    chance: 18,
    xp: 17,
    description: "A broad carp with warm scales and a stubborn side pull.",
    colors: ["#f4b657", "#8d5a28"],
  },
  {
    id: "moss-catfish",
    name: "Moss Catfish",
    rarity: "Rare",
    minWeight: 3.4,
    maxWeight: 11.8,
    basePrice: 54,
    locations: ["lake"],
    zones: ["deep"],
    chance: 8,
    xp: 32,
    description: "A whiskered bottom dweller that drags the line through weeds.",
    colors: ["#6f8f61", "#263c2e"],
  },
  {
    id: "lantern-koi",
    name: "Lantern Koi",
    rarity: "Epic",
    minWeight: 2.2,
    maxWeight: 8.4,
    basePrice: 92,
    locations: ["lake"],
    zones: ["deep"],
    chance: 2.2,
    xp: 56,
    description: "A glowing lake prize said to rise only when the water goes still.",
    colors: ["#ffdf7f", "#ff7d67"],
  },
  {
    id: "mudwhisker",
    name: "Mudwhisker",
    rarity: "Common",
    minWeight: 0.9,
    maxWeight: 4.4,
    basePrice: 24,
    locations: ["swamp"],
    zones: ["near"],
    chance: 36,
    xp: 15,
    description: "A patient swamp fish that follows shadows along muddy shelves.",
    colors: ["#8b8152", "#314328"],
  },
  {
    id: "lilyshade-perch",
    name: "Lilyshade Perch",
    rarity: "Uncommon",
    minWeight: 0.7,
    maxWeight: 3.2,
    basePrice: 38,
    locations: ["swamp"],
    zones: ["near", "far"],
    chance: 24,
    xp: 24,
    description: "It hides under lily pads until the bait drifts a little too close.",
    colors: ["#b7c984", "#42623a"],
  },
  {
    id: "siltback-gar",
    name: "Siltback Gar",
    rarity: "Rare",
    minWeight: 3.8,
    maxWeight: 16.5,
    basePrice: 96,
    locations: ["swamp"],
    zones: ["far", "deep"],
    chance: 9,
    xp: 50,
    description: "A long armored hunter that fights in slow, heavy lunges.",
    colors: ["#96a26f", "#273322"],
  },
  {
    id: "bog-lantern-carp",
    name: "Bog Lantern Carp",
    rarity: "Epic",
    minWeight: 2.4,
    maxWeight: 10.2,
    basePrice: 142,
    locations: ["swamp"],
    zones: ["deep"],
    chance: 2.4,
    xp: 74,
    description: "A soft green glow flickers along its back before it dives.",
    colors: ["#c4ef86", "#365c34"],
  },
  {
    id: "crownmire-eel",
    name: "Crownmire Eel",
    rarity: "Legendary",
    minWeight: 4.5,
    maxWeight: 19.5,
    basePrice: 310,
    locations: ["swamp"],
    zones: ["deep"],
    chance: 0.9,
    xp: 128,
    description: "A rare eel with gold flecks that coils around submerged roots.",
    colors: ["#f5c95c", "#263a2e"],
  },
  {
    id: "quickfin-dace",
    name: "Quickfin Dace",
    rarity: "Common",
    minWeight: 0.3,
    maxWeight: 1.5,
    basePrice: 12,
    locations: ["river"],
    zones: ["near"],
    chance: 38,
    xp: 10,
    description: "A current-loving fish that darts in short silver bursts.",
    colors: ["#d6e7e0", "#4d927f"],
  },
  {
    id: "silver-trout",
    name: "Silver Trout",
    rarity: "Uncommon",
    minWeight: 1.3,
    maxWeight: 4.8,
    basePrice: 32,
    locations: ["river"],
    zones: ["near", "far"],
    chance: 24,
    xp: 20,
    description: "A clean river trout that uses the current as a second tail.",
    colors: ["#d9edf0", "#6389a7"],
  },
  {
    id: "canyon-pike",
    name: "Canyon Pike",
    rarity: "Rare",
    minWeight: 4.2,
    maxWeight: 13.5,
    basePrice: 72,
    locations: ["river"],
    zones: ["far", "deep"],
    chance: 9,
    xp: 40,
    description: "A lean ambush fish that slashes from bank shade to open flow.",
    colors: ["#b8c46f", "#5f4a2d"],
  },
  {
    id: "storm-eel",
    name: "Storm Eel",
    rarity: "Epic",
    minWeight: 2.8,
    maxWeight: 9.8,
    basePrice: 112,
    locations: ["river"],
    zones: ["deep"],
    chance: 2.6,
    xp: 64,
    description: "Its blue streaks twitch like lightning when rain hits the river.",
    colors: ["#b798ff", "#36506f"],
  },
  {
    id: "frost-pebble-char",
    name: "Frost Pebble Char",
    rarity: "Common",
    minWeight: 0.6,
    maxWeight: 2.8,
    basePrice: 31,
    locations: ["mountain"],
    zones: ["near"],
    chance: 33,
    xp: 18,
    description: "A cold-water char that nips from beneath rounded mountain stones.",
    colors: ["#d9edf0", "#5c7c92"],
  },
  {
    id: "snowglass-trout",
    name: "Snowglass Trout",
    rarity: "Uncommon",
    minWeight: 1.5,
    maxWeight: 6.2,
    basePrice: 64,
    locations: ["mountain"],
    zones: ["near", "far"],
    chance: 22,
    xp: 34,
    description: "A clear-finned trout with a fast, icy shake on the line.",
    colors: ["#f2f7f4", "#6aa9bf"],
  },
  {
    id: "granite-sturgeon",
    name: "Granite Sturgeon",
    rarity: "Rare",
    minWeight: 8,
    maxWeight: 28,
    basePrice: 156,
    locations: ["mountain"],
    zones: ["far", "deep"],
    chance: 7,
    xp: 68,
    description: "A slab-sided sturgeon that feels like reeling a stone uphill.",
    colors: ["#aab7bd", "#435765"],
  },
  {
    id: "aurora-salmon",
    name: "Aurora Salmon",
    rarity: "Epic",
    minWeight: 4.6,
    maxWeight: 15.5,
    basePrice: 230,
    locations: ["mountain"],
    zones: ["deep"],
    chance: 2.1,
    xp: 105,
    description: "Its scales shimmer with cold color when it turns under moonlight.",
    colors: ["#b798ff", "#59c7f2"],
  },
  {
    id: "whiteout-leviathan",
    name: "Whiteout Leviathan",
    rarity: "Mythical",
    minWeight: 22,
    maxWeight: 70,
    basePrice: 560,
    locations: ["mountain"],
    zones: ["deep"],
    chance: 0.55,
    xp: 190,
    description: "A mountain myth that pulls hard enough to silence the whole lake.",
    colors: ["#ffffff", "#78a9d4"],
  },
  {
    id: "foam-mackerel",
    name: "Foam Mackerel",
    rarity: "Common",
    minWeight: 0.8,
    maxWeight: 3.2,
    basePrice: 19,
    locations: ["ocean"],
    zones: ["near"],
    chance: 36,
    xp: 14,
    description: "A surf-school fish that flashes through broken foam.",
    colors: ["#cbeef1", "#1d7fa9"],
  },
  {
    id: "coral-snapper",
    name: "Coral Snapper",
    rarity: "Uncommon",
    minWeight: 2,
    maxWeight: 7.6,
    basePrice: 46,
    locations: ["ocean", "coral"],
    zones: ["far"],
    chance: 22,
    xp: 26,
    description: "A sharp red snapper that patrols reef cuts and deeper surf.",
    colors: ["#ff977a", "#9a3144"],
  },
  {
    id: "royal-tuna",
    name: "Royal Tuna",
    rarity: "Rare",
    minWeight: 8.5,
    maxWeight: 32,
    basePrice: 128,
    locations: ["ocean"],
    zones: ["far", "deep"],
    chance: 8,
    xp: 58,
    description: "A heavy blue runner that turns every reel fight into a sprint.",
    colors: ["#59c7f2", "#153e68"],
  },
  {
    id: "dusk-ray",
    name: "Dusk Ray",
    rarity: "Legendary",
    minWeight: 12,
    maxWeight: 40,
    basePrice: 260,
    locations: ["ocean"],
    zones: ["deep"],
    chance: 1.2,
    xp: 105,
    description: "A broad ray that rises at sundown with a gold rim on its wings.",
    colors: ["#f5c95c", "#7252a3"],
  },
  {
    id: "prism-wrasse",
    name: "Prism Wrasse",
    rarity: "Common",
    minWeight: 0.4,
    maxWeight: 1.7,
    basePrice: 34,
    locations: ["coral"],
    zones: ["near"],
    chance: 31,
    xp: 20,
    description: "A bright reef fish that flickers through coral branches.",
    colors: ["#59c7f2", "#ff7dcb"],
  },
  {
    id: "ember-parrotfish",
    name: "Ember Parrotfish",
    rarity: "Uncommon",
    minWeight: 1.6,
    maxWeight: 6.8,
    basePrice: 76,
    locations: ["coral"],
    zones: ["near", "far"],
    chance: 18,
    xp: 42,
    description: "A warm-colored grazer that crunches coral and runs in circles.",
    colors: ["#ff7d67", "#f5c95c"],
  },
  {
    id: "sapphire-needlefish",
    name: "Sapphire Needlefish",
    rarity: "Rare",
    minWeight: 2.2,
    maxWeight: 9,
    basePrice: 138,
    locations: ["coral"],
    zones: ["far"],
    chance: 7,
    xp: 72,
    description: "A slim blue hunter that makes the reel marker twitch fast.",
    colors: ["#59c7f2", "#114c76"],
  },
  {
    id: "gilded-grouper",
    name: "Gilded Grouper",
    rarity: "Epic",
    minWeight: 10,
    maxWeight: 36,
    basePrice: 285,
    locations: ["coral"],
    zones: ["far", "deep"],
    chance: 2.4,
    xp: 118,
    description: "A reef heavyweight with gold plates and a brutal first dive.",
    colors: ["#f5c95c", "#e08f72"],
  },
  {
    id: "sunken-crownfish",
    name: "Sunken Crownfish",
    rarity: "Legendary",
    minWeight: 5.5,
    maxWeight: 19,
    basePrice: 420,
    locations: ["coral"],
    zones: ["deep"],
    chance: 0.75,
    xp: 170,
    description: "A jeweled fish that hides near old wreckage in the brightest bay.",
    colors: ["#ffd36b", "#ff7dcb"],
  },
  {
    id: "starlit-manta",
    name: "Starlit Manta",
    rarity: "Secret",
    minWeight: 18,
    maxWeight: 62,
    basePrice: 980,
    locations: ["coral", "abyss"],
    zones: ["deep"],
    chance: 0.18,
    xp: 280,
    description: "A secret manta whose back looks like a sky reflected underwater.",
    colors: ["#ffffff", "#8ffcff"],
  },
  {
    id: "veil-angler",
    name: "Veil Angler",
    rarity: "Mythical",
    minWeight: 4.8,
    maxWeight: 18,
    basePrice: 340,
    locations: ["abyss"],
    zones: ["near", "far"],
    chance: 4,
    xp: 135,
    description: "A deep-water glowfish with a drifting lure like pale silk.",
    colors: ["#ff7dcb", "#27335c"],
  },
  {
    id: "static-phantom",
    name: "Static Phantom",
    rarity: "Secret",
    minWeight: 0.6,
    maxWeight: 3.6,
    basePrice: 620,
    locations: ["abyss"],
    zones: ["deep"],
    chance: 0.55,
    xp: 220,
    description: "A glitch-bright fish that appears as a flash before the line screams.",
    colors: ["#ffffff", "#8ffcff"],
  },
  // --- Harbor Fish ---
  {
    id: "harbor-herring",
    name: "Гаванський Оселедець",
    rarity: "Common",
    minWeight: 0.3,
    maxWeight: 1.4,
    basePrice: 14,
    locations: ["harbor"],
    zones: ["near", "far"],
    chance: 42,
    xp: 10,
    description: "Срібляста зграйна рибка, що кружляє біля опор причалу гавані.",
    colors: ["#d0e6f5", "#487194"],
  },
  {
    id: "dock-flounder",
    name: "Причальна Камбала",
    rarity: "Uncommon",
    minWeight: 0.8,
    maxWeight: 3.5,
    basePrice: 32,
    locations: ["harbor"],
    zones: ["near", "deep"],
    chance: 26,
    xp: 22,
    description: "Пласка маскуюча риба, що лежить на піщаному дні біля човнів.",
    colors: ["#c7a77e", "#5a4329"],
  },
  {
    id: "golden-bass",
    name: "Золотистий Окунь",
    rarity: "Rare",
    minWeight: 2.2,
    maxWeight: 7.8,
    basePrice: 78,
    locations: ["harbor"],
    zones: ["far", "deep"],
    chance: 11,
    xp: 45,
    description: "Міцний гаванський боєць із золотистим відливом на плавцях.",
    colors: ["#ffd768", "#7b5016"],
  },
  {
    id: "captain-snapper",
    name: "Капітанський Люціан",
    rarity: "Epic",
    minWeight: 4.5,
    maxWeight: 14.0,
    basePrice: 165,
    locations: ["harbor"],
    zones: ["deep"],
    chance: 3.2,
    xp: 88,
    description: "Гордість місцевих рибалок, що полює на глибині біля маяка.",
    colors: ["#ff7360", "#8f1922"],
  },

  // --- Bog Lake Fish ---
  {
    id: "mire-bullhead",
    name: "Топковий Сомик",
    rarity: "Common",
    minWeight: 0.6,
    maxWeight: 2.8,
    basePrice: 22,
    locations: ["bog"],
    zones: ["near"],
    chance: 38,
    xp: 16,
    description: "Вусатий мешканець темного мулу під корінням болотяних кипарисів.",
    colors: ["#857448", "#2c2214"],
  },
  {
    id: "bog-pike",
    name: "Болотна Щука",
    rarity: "Rare",
    minWeight: 3.5,
    maxWeight: 12.0,
    basePrice: 92,
    locations: ["bog"],
    zones: ["near", "far"],
    chance: 16,
    xp: 52,
    description: "Замаскована хижачка з плямами кольору моху та гострими зубами.",
    colors: ["#8cb04a", "#2f4019"],
  },
  {
    id: "wisp-tetra",
    name: "Вогникова Тетра",
    rarity: "Epic",
    minWeight: 0.4,
    maxWeight: 1.9,
    basePrice: 175,
    locations: ["bog"],
    zones: ["far", "deep"],
    chance: 4.5,
    xp: 92,
    description: "Мерехтить зеленими іскрами, немов живий блукаючий болотний вогник.",
    colors: ["#bbf85a", "#386b24"],
  },
  {
    id: "witchmire-turtle",
    name: "Містична Болотяна Черепаха",
    rarity: "Legendary",
    minWeight: 6.0,
    maxWeight: 22.0,
    basePrice: 380,
    locations: ["bog"],
    zones: ["deep"],
    chance: 1.4,
    xp: 160,
    description: "Стародавня істота, на панцирі якої росте віковий болотний мох.",
    colors: ["#488a5e", "#cfa43c"],
  },
  {
    id: "ancient-bog-lurker",
    name: "Стародавній Глибинник Топей",
    rarity: "Mythical",
    minWeight: 14.0,
    maxWeight: 45.0,
    basePrice: 680,
    locations: ["bog"],
    zones: ["deep"],
    chance: 0.7,
    xp: 230,
    description: "Гігантський релікт боліт, що підіймає хвилі та туман при підсіканні.",
    colors: ["#32522c", "#8dffbc"],
  },

  // --- Underground Cavern Lake (Level 10+) Fish ---
  {
    id: "blind-cavefish",
    name: "Сліпа Печерна Рибка",
    rarity: "Uncommon",
    minWeight: 0.5,
    maxWeight: 2.2,
    basePrice: 85,
    locations: ["cavern"],
    zones: ["near"],
    chance: 34,
    xp: 50,
    description: "Бліда напівпрозора риба, що ідеально відчуває вібрації у темряві печер.",
    colors: ["#f5ebeb", "#a88e9f"],
  },
  {
    id: "crystal-tetra",
    name: "Кришталева Тетра",
    rarity: "Rare",
    minWeight: 0.7,
    maxWeight: 2.9,
    basePrice: 180,
    locations: ["cavern"],
    zones: ["near", "far"],
    chance: 18,
    xp: 95,
    description: "Сяє бірюзовими гранями кристалів у прохолодній підземній воді.",
    colors: ["#76f5f0", "#216885"],
  },
  {
    id: "abyssal-axolotl",
    name: "Глибинний Аксолотль",
    rarity: "Epic",
    minWeight: 1.8,
    maxWeight: 6.5,
    basePrice: 360,
    locations: ["cavern"],
    zones: ["far", "deep"],
    chance: 5.5,
    xp: 160,
    description: "Рідкісна печерна амфібія з пухнастими неоново-рожевими зябрами.",
    colors: ["#ff9cd5", "#5c2a70"],
  },
  {
    id: "glow-grotto-eel",
    name: "Сяючий Гротовий Вугор",
    rarity: "Legendary",
    minWeight: 5.2,
    maxWeight: 18.5,
    basePrice: 620,
    locations: ["cavern"],
    zones: ["deep"],
    chance: 1.8,
    xp: 240,
    description: "Гнучкий вугор, що освітлює підземні скелі бірюзовими блискавками.",
    colors: ["#4df3ff", "#13285c"],
  },
  {
    id: "void-sturgeon",
    name: "Осетер Порожнечі",
    rarity: "Mythical",
    minWeight: 15.0,
    maxWeight: 55.0,
    basePrice: 1050,
    locations: ["cavern"],
    zones: ["deep"],
    chance: 0.85,
    xp: 380,
    description: "Величезний темний осетер з фіолетовими кристалічними наростами.",
    colors: ["#c594ff", "#160e29"],
  },
  {
    id: "crystal-leviathan",
    name: "Кришталевий Левіафан",
    rarity: "Secret",
    minWeight: 28.0,
    maxWeight: 90.0,
    basePrice: 1850,
    locations: ["cavern"],
    zones: ["deep"],
    chance: 0.28,
    xp: 580,
    description: "Господар підземних вод із панциром із чистого кристалу та лютим норовом.",
    colors: ["#ffffff", "#42f5e9"],
  },
].map((fish) => ({ ...fish, archetype: getFishArchetype(fish) })));

export function getFishById(id) {
  return fishDatabase.find((fish) => fish.id === id) ?? null;
}

export function getLocationMeta(id) {
  return LOCATION_META[id] ?? LOCATION_META.lake;
}

export function getCastZone(power) {
  const clampedPower = clamp(power, 0, 1);
  return CAST_ZONES.find((zone) => clampedPower >= zone.minPower && clampedPower <= zone.maxPower) ?? CAST_ZONES[0];
}

export function getFishPool(locationId, zoneId) {
  const exactPool = fishDatabase.filter(
    (fish) => fish.locations.includes(locationId) && fish.zones.includes(zoneId),
  );

  if (exactPool.length > 0) {
    return exactPool;
  }

  return fishDatabase.filter((fish) => fish.locations.includes(locationId));
}

// Rolls a fish from a weighted local pool. Bait and rod luck favor rare fish
// without completely removing common catches from the economy.
export function rollFish({ locationId, zoneId, luckBonus = 0 }) {
  const pool = getFishPool(locationId, zoneId);
  const weightedPool = pool.map((fish) => {
    const rarity = RARITY_META[fish.rarity] ?? RARITY_META.Common;
    const luckScale = 1 + luckBonus * rarity.difficulty * 1.85;
    const zoneScale = fish.zones.includes(zoneId) ? 1 : 0.35;
    return {
      fish,
      weight: fish.chance * luckScale * zoneScale,
    };
  });

  const totalWeight = weightedPool.reduce((sum, entry) => sum + entry.weight, 0);
  let roll = Math.random() * totalWeight;

  for (const entry of weightedPool) {
    roll -= entry.weight;
    if (roll <= 0) {
      return entry.fish;
    }
  }

  return weightedPool[weightedPool.length - 1]?.fish ?? fishDatabase[0];
}

export function createCatch(fish, { locationId, zoneId }) {
  const weight = roundTo(randomBetween(fish.minWeight, fish.maxWeight), 2);
  const averageWeight = (fish.minWeight + fish.maxWeight) / 2;
  const rarity = RARITY_META[fish.rarity] ?? RARITY_META.Common;
  const weightValue = 0.72 + (weight / averageWeight) * 0.38;
  const price = Math.max(1, Math.round(fish.basePrice * rarity.priceScale * weightValue));

  return {
    catchId: makeCatchId(),
    fishId: fish.id,
    name: fish.name,
    rarity: fish.rarity,
    archetype: fish.archetype,
    weight,
    price,
    xp: fish.xp,
    description: fish.description,
    colors: fish.colors,
    locationId,
    zoneId,
    caughtAt: new Date().toISOString(),
  };
}

export function getCatchDifficulty(catchItem) {
  const fish = getFishById(catchItem.fishId);
  const rarity = RARITY_META[catchItem.rarity] ?? RARITY_META.Common;

  if (!fish) {
    return rarity.difficulty;
  }

  const weightRange = fish.maxWeight - fish.minWeight || 1;
  const weightRatio = (catchItem.weight - fish.minWeight) / weightRange;
  return clamp(rarity.difficulty + weightRatio * 0.18, 0.08, 1.18);
}

function randomBetween(min, max) {
  return min + Math.random() * (max - min);
}

function roundTo(value, places) {
  const factor = 10 ** places;
  return Math.round(value * factor) / factor;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function makeCatchId() {
  if (globalThis.crypto?.randomUUID) {
    return globalThis.crypto.randomUUID();
  }

  return `catch-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}
